const {Sequelize,DataTypes}=require('sequelize')

module.exports=(sequelize,DataTypes)=>{
    const organizationModel=sequelize.define('organizationModel',{
            organizationName:{
                type:DataTypes.STRING,
                allowNull:false
            },
            organizationEmail:{
                type:DataTypes.STRING,
                allowNull:false
            },
            organizationMobile:{
                type:DataTypes.DECIMAL,
                allowNull:false
            },
            organizationType:{
                type:sequelize.ENUM("Medical","Study","Charity"),
                allowNull:false
            },
            organizationAddress:{
                type:DataTypes.STRING,
                allowNull:false
            },
            whySelect:{
                type:DataTypes.TEXT
            },
            governmentCertified:{
                type:DataTypes.BOOLEAN,
                defaultValue:false
            },
            updatedBy:{
                type:DataTypes.STRING
            }, 
            updatedOn:{
                type:DataTypes.DATE
            },
            acceptBy:{
                type:DataTypes.STRING
            },
            acceptOn:{
                type:DataTypes.DATE
            },
            status:{
                type:Sequelize.ENUM("Pending","Approved","Rejected"),
                allowNull:false
            },
            random_value:{
                type:DataTypes.STRING
            }
    }); 
    return organizationModel
}